# Generated by Django 3.0.5 on 2020-05-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_auto_20181028_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinstance',
            name='book',
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='borrower',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='book',
            name='summary',
        ),
        migrations.AddField(
            model_name='book',
            name='bookcase',
            field=models.CharField(default=' ', max_length=3),
        ),
        migrations.AddField(
            model_name='book',
            name='format',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='book',
            name='other',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='shelf',
            field=models.CharField(default=' ', max_length=3),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='BookInstance',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
